# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::373952420897:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-oErMHxavH22c
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::373952420897:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-26T13:03:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1445"
  uid: 2e41b9e2-7874-49ee-924d-2ba067c8df51
